/* eslint-disable @next/next/no-img-element */

import type {
  GetServerSideProps,
  InferGetServerSidePropsType,
  NextPage,
} from 'next'
import { getSession } from 'next-auth/react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useGetUserCopiesQuery } from '../services/copyApi'

const Home: NextPage = ({}: InferGetServerSidePropsType<
  typeof getServerSideProps
>) => {
  const { data } = useGetUserCopiesQuery('XL2')

  const router = useRouter()

  const handleStartClick = () => router.push('/auth/login')

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='hero min-h-screen bg-base-200'>
        <div className='hero-content flex-col lg:flex-row'>
          <img
            src='https://placeimg.com/260/400/arch'
            className='max-w-sm rounded-lg shadow-2xl'
            alt=''
          />
          <div>
            <h1 className='text-5xl font-bold'>Box Office News!</h1>
            <p className='py-6'>
              Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda
              excepturi exercitationem quasi. In deleniti eaque aut repudiandae
              et a id nisi.
            </p>
            <button className='btn btn-primary' onClick={handleStartClick}>
              Get Started
            </button>
          </div>
        </div>
      </div>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const data = await getSession({ req })

  // redicts if finds data

  if (data) {
    return {
      redirect: {
        permanent: false,
        destination: '/home',
      },
    }
  }

  return {
    props: {},
  }
}

export default Home
